image: docker.repo.splunkdev.net/ci-cd/ci-container/golang-1.19:1.1.0

include:
  - project: "ci-cd/templates"
    ref: master
    file: "/prodsec/.oss-scan.yml"
  - project: "prodsec/scp-scanning/gitlab-checkmarx"
    ref: latest
    file: "/templates/.sast_scan.yml"
  - project: core-ee/cicd-building-blocks
    ref: feature/INFRA-37105-add-wft-support
    file: wf-actions-trigger-2.1.0.yml

stages:
  - build
  - e2e
  - scanning
  - publish

oss-scan:
  extends: .oss-scan
  stage: scanning
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH)'

sast-scanner:
  stage: scanning
  extends: .sast_scan
  variables:
    CX_PROJECT_ID: 17697
    TRANSPILE_JSX: 1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH)'

build:
  stage: build
  script:
    - make
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH)'

publish:
  dependencies:
    - build
  stage: publish
  script:
    - make build publish
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH'

e2e:
  stage: e2e
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH)'
  extends: .trigger-workflow
  variables:
    WORKFLOW_FILE: argocd-vault-plugin-integration-tests
    ARGO_NAMESPACE: argocd-tokens-vault-plugin-testing
    WFE_CLUSTER: wfe
    IS_WORKFLOW_TEMPLATE: "true"