apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base
- ./resources

patchesStrategicMerge: 
- ./patch/argocd-application-controller.yaml
- ./patch/argocd-applicationset-controller.yaml
- ./patch/argocd-cm.yaml
- ./patch/argocd-rbac-cm.yaml
- ./patch/argocd-notifications-controller.yaml
- ./patch/argocd-redis.yaml
- ./patch/argocd-repo-server.yaml
- ./patch/argocd-server.yaml

