name: Scan
on:
  push:
    tags:
      - v*.*.*
    branches:
      - main
      - release/v*.*.*
  pull_request:
    branches:
     - main
     - release/v*.*.*
permissions:
  contents: read
jobs:
  fossa-scan:
    uses: splunk/oss-scanning-public/.github/workflows/oss-scan.yml@main
    secrets: inherit
  SAST:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_KEY }}

