name: Test
on:
  push:
    tags:
      - v*.*.*
    branches:
      - main
      - release/v*.*.*
  pull_request:
    branches:
     - main
     - release/v*.*.*
permissions:
  contents: read
  pull-requests: read
jobs:
  Test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Unit Test
        run: make test      